language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 rapidjson-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BUILD_TYPE=Debug"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BUILD_TYPE=RelWithDebInfo"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && BUILD_TYPE=Debug"
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && BUILD_TYPE=RelWithDebInfo"
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="BUILD_TYPE=Debug"
        - MATRIX_EVAL="BUILD_TYPE=RelWithDebInfo"

before_install:
  - eval "${MATRIX_EVAL}"

script: cd libjsonutils && mkdir cmake-build && cd cmake-build && cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"" .. && make && make test
