language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++-7 
            - rapidjson-dev 
            - libboost1.67-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-xenial-6.0
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - clang-6.0 
            - rapidjson-dev
            - libboost1.67-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - boost 
            - rapidjson
      env:
        - MATRIX_EVAL=""

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - cd libjsonutils

script: 
  - mkdir cmake-build-debug && cd cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && make test
  - cd .. && mkdir cmake-build-relwithdebinfo && cd cmake-build-relwithdebinfo && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && make && make test
